FROM alpine:latest
MAINTAINER Feng George Yu <fyu@ysu.edu>

RUN apk update && \
	apk add --no-cache bash vim htop wget \
		gcc g++ gdb readline-dev zlib-dev git bison flex flex-dev \
		perl-utils perl-ipc-run perl-dev







